name: Publish Docker Image (Production)

on:
  push:
    branches:
      - main

jobs:
  
  publish-docker-image:
    runs-on: docker
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to JWA Container Registry
        uses: docker/login-action@v3
        with:
          registry: repo.jouleworks.net
          username: yuu
          password: ${{ secrets.ACCESS_TOKEN_DOCKER_REPO }}

      - name: Build the production Backend Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: repo.jouleworks.net/apps/svin.space:latest